version: "3"
services:
  db:
    image: "postgres"
    container_name: "aviasales_postgres"
    environment:
      - POSTGRES_USER=aviasales
      - POSTGRES_PASSWORD=aviasales
      - POSTGRES_DB=hotels
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql